services:
  - type: web
    name: woofbuddy
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: python -m gunicorn grooming.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: grooming.settings_prod
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
    autoDeploy: true
