# Generated by Django 5.2 on 2026-04-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_pet_gender_pet_medical_conditions_pet_weight_kg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='weight_kg',
        ),
        migrations.AddField(
            model_name='pet',
            name='animal_type',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Bird', 'Bird'), ('Rabbit', 'Rabbit'), ('Other', 'Other')], default='Dog', max_length=20),
        ),
    ]
